# Generated by Django 5.2.4 on 2025-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_created_at_product_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Supplements', 'Supplements'), ('Clothing', 'Clothing'), ('Books', 'Books')], default='General', max_length=50, null=True, verbose_name='Category'),
        ),
    ]
